export const BASE_URL = "http://localhost:4000/api/v2" ;

export const LOGIN_REQUEST = "LOGIN_REQUEST" ;
export const LOGIN_SUCCESS = "LOGIN_SUCCESS" ;
export const LOGIN_FAIL =    "LOGIN_FAIL" ;

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST" ;
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS" ;
export const REGISTER_USER_FAIL =    "REGISTER_USER_FAIL" ;

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST" ;
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS" ;
export const LOAD_USER_FAIL =    "LOAD_USER_FAIL" ;

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS" ;
export const LOGOUT_USER_FAIL =    "LOGOUT_USER_FAIL" ;

export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST" ;
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS" ;
export const ALL_USERS_FAIL =    "ALL_USERS_FAIL" ;

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST" ;
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS" ;
export const DELETE_USER_RESET = "DELETE_USER_RESET" ;
export const DELETE_USER_FAIL =    "DELETE_USER_FAIL" ;

export const CLEAR_ERRORS= "CLEAR_ERRORS" ;